### ISSUE TITLE
MSU-1 Support

### ISSUE THREAD

**Issue by Nigoli** [Her-Saki/Rockman_X3#1]
Hello,

Thank you for making another faithful translation patch like the first two games. Unfortunately MSU-1 support doesn't work here and will need to be shifted to another location like X2's patch I'm assuming for those hooks to work for anybody interested in playing the translation with MSU-1 audio.

I'm going to link Conn to the issue. I'm still very grateful for the info he gave so that the X2 translation patch could work with the MSU-1 patch.

Will test with a full playthrough like last time.

**Comment by ghost** [comment]
Yes, the issue is the same like last time. It isn't my msu1 patch, so I don't have a source (author darkshock).

If you could move the code at pc 0x7e5d to 0x7d20 
`org $FE5D
MainJump:` 
-> FD20

and the code at 0x7ef0 (ASCII says "Capcom" to 0x7d50 it should be compatible with the msu code ;)

**Comment by Her-Saki** [comment]
That's odd. Virtually all the code was written outside that region on
purpose to avoid mirroring a new version for MSU... but never mind, I'll
mirror it later.
Best regards.

**Comment by Her-Saki** [comment]
>$FD20 is not empty in the Japanese version.
>I have no way to move that CAPCOM string, since it's present in the original, without further ASM (I could do it if it's really necessary though).

**Comment by ghost** [comment]
My fault really sorry. Yes. CAPCOM is no conflict at all. It is just the code at  $7e5d. I just see that 7f80 isn't used by msu1, and your code here needs less than $30 bytes.
Can you move it to $7f80? That's also free in rockman x3

**Comment by Her-Saki** [comment]
Check the new patch.

**Comment by Nigoli** [comment]
I did a 100% playthrough with all optional bosses defeated without getting Zero's Beam Saber & Hyper Chip.

Didn't have any problems. Awesome translation that's faithful to the original's dialogue.

Thanks again guys.
